AWSTemplateFormatVersion: "2010-09-09"

Description: |
  A macro that takes in a Cloudformation template,

Transform:
  - "AWS::Serverless-2016-10-31"

Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: CfnMacroPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogDelivery"
                  - "logs:PutLogEvents"
                  - "s3:*"
                Resource:
                  - "*"

  DepLayer:
    Type: "PythonLayer"
    Transform:
      Name: PythonLambdaLayer
    Properties:
      BucketName: test
      CompatibleRuntimes:
        - python3.8
      LayerName: camelcase
      Package:
        name: camelcase
        version: "0.2"

  Function:
    Type: "AWS::Serverless::Function"
    DependsOn: StepfunctionsDepLayer
    Properties:
      CodeUri: src/
      Handler: app.handler
      Layers:
        - !Ref StepfunctionsDepLayer
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python3.8
      Timeout: 30

  CfnMacro:
    Type: "AWS::CloudFormation::Macro"
    Properties:
      FunctionName: !GetAtt Function.Arn
      Name: DataScienceSDK

Outputs:
  FunctionArn:
    Description: Arn of created function
    Value: !GetAtt Function.Arn
